// assets/js/pages/Index.svelte
<script>
    import { useForm } from "@inertiajs/svelte";

    // Props
    const { name, items } = $props();

    // Form
    let form = useForm({
        name: "",
        email: "",
    });
</script>

<svelte:head>
    <title>Hello, {name}!</title>
    <meta name="description" content="Page for {name} with their items" />
</svelte:head>

<h1 class="text-2xl font-semibold">Hello, {name}!</h1>
<ul class="list-disc pl-6 space-y-2 mt-4">
    {#each items as item}
        <li>{item}</li>
    {/each}
</ul>

// assets/js/pages/Index.tsx
import React from "react";
import { Link } from "@inertiajs/react";

type Props = {
  items: string[];
};

const Index = ({ items }: Props) => {
  return (
    <>
      <h1 className="text-3xl font-semibold">Check out these items:</h1>
      <ul className="list-disc list-inside mt-4">
        {items.map((item, index) => (
          <li key={index}>{item}</li>
        ))}
      </ul>
      <Link className="btn mt-4" href="/cars">
        Go to cars
      </Link>
    </>
  );
};

export default Index;
